# Generated by Django 3.1.5 on 2021-01-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emproutines',
            name='weekdays',
            field=models.CharField(max_length=200),
        ),
    ]
