# Generated by Django 3.1.5 on 2021-01-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210111_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Client', 'Client')], default='Client', max_length=10),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
